{% macro generate_from_dictionary_source_yml(database_name='default', version_name='default', is_external='false', description_method='none',apply_filter=' ') %}

    {% if database_name=='default' %}
        {% set database_name = var('dictionary_database', target.database) %}
    {% endif %}
    {% if version_name=='default' %}
        {% set version_name = var('dictionary_database_version', 'default') %}
    {% endif %}

    {% if is_external == 'false' %}
        {% set source_name = 'raw__' ~ database_name | lower %}
        {% set source_description = '\'[[ doc("' ~ database_name ~ '_source_description'  ~ '") ]]\'' %}
        {% set source_database = 'raw' %}
        {% set source_schema = database_name %}
    {% else %}
        {% set source_name = database_name | lower %}
        {% set source_description = 'None Provided' %}
        {% set source_database = database_name %}
        {% set source_schema = 'public' %}
    {% endif %}

{% set header %}
#
#   This file was originally generated by the macro generate_from_dictionary_source_yml and is now under manual control. Replacing with a regenerated file will lose changes!!
#

version: 2

sources:
  - name: {{source_name}}
    description: {{source_description}}
    database: {{source_database}}
    schema:  {{source_schema}}
    loader:  Manual

    tables:
{%- endset -%}

      {% set query %}
    	select  
            source_table_name, stage_table_name, source_column_name, stage_column_description
            , stage_column_name, source_column_type, lower(stage_column_type) stage_column_type, allow_null
            , CASE WHEN '{{is_external}}' = 'false' then source_table_name else stage_table_name end as table_name
            , CASE WHEN '{{is_external}}' = 'false' then source_column_name else stage_column_name end as column_name
            , CASE WHEN '{{is_external}}' = 'false' then source_column_type else stage_column_type end as column_type
            , CASE WHEN '{{is_external}}' = 'false' then '_source_description' else '_stage_description' end as suffix
	    from internal.data_dictionary 
        where 
            database_name='{{database_name}}' and version_name='{{version_name}}' 
	    and stage_table_name like 'loandetails%'
            {{ apply_filter }}
	    order by source_table_name, column_order
   
    {% endset %}
   {% set header = header | string | replace('(*', '{%') | replace('*)', '%}') | replace('[[', '{{') | replace(']]', '}}') %}
    {% do print (header) %}

    {% set rowset=run_query(query) %}

   {% set ns = namespace(last_table_name = 'NOT SET') %}
       {% set sources_yaml=[] %}
    {% for col in rowset %}
        {% set current_table_name = col.TABLE_NAME | string %}      
        {% if not ns.last_table_name  == current_table_name %}
          {% set joined = sources_yaml | join ('\n') %}
          {% set sources_yaml=[] %}
	        {% if is_external == 'false' %}
                {% do print('      - name: "' ~  col.TABLE_NAME ~ '"') %}
            {% else %}
                {% do print('      - name: ' ~  col.TABLE_NAME ) %}
            {% endif %}
            {% if description_method == 'reference' %}
                    {% do print('        description: \'{{ doc("' ~ database_name ~ '_' ~ col.TABLE_NAME ~ col.SUFFIX ~ '") }}\'') %}  
            {% elif description_method == 'direct' %}
                {% do print('        description: "Not Provided"' )  %}   
            {% endif %}
            {% do print('        columns:') %}
            {% set ns.last_table_name = col.TABLE_NAME | string %}
        {%endif %}

  	     {% if is_external == 'false' %}
            {% do print('          - name: "' ~ col.COLUMN_NAME ~ '"') %}
         {% else %}
            {% do print('          - name: ' ~ col.COLUMN_NAME ) %}
         {% endif %}
        {% do print('            data_type: ' ~ col.COLUMN_TYPE ) %}
        {% do print('            quote: true' ) %}
        {% if description_method == 'reference' %}
            {% do print('            description: \'{{ doc("' ~ database_name ~ '_' ~ col.TABLE_NAME ~ '_' ~ col.COLUMN_NAME ~ col.SUFFIX ~ '") }}\'') %}  
        {% elif description_method == 'direct' %}
            {% do print('            description: "' ~ col.STAGE_COLUMN_DESCRIPTION ~ '"' )  %}   
        {% endif %}        
        {% if col.ALLOW_NULL == false %}
            {% do sources_yaml.append('            tests: ' ) %}
            {% do sources_yaml.append('              - not_null' ) %}
        {% endif %}
        {% do sources_yaml.append('') %}
    {% endfor %}

{% endmacro %}
